### ISSUE TITLE
[Request] Windows Package support

### ISSUE THREAD

**Issue by bachig26** [gmt4/mpvc#4]
This is an request for supporting the Windows device and possible release of the packages for it.

**Comment by gmt4** [comment]
Hi there, 
The current focus is on UNIX/Linux OSes.
Any idea on how Windows support could be achieved?
Thanks.

**Comment by gmt4** [comment]
Thanks, for now I've update the FAQ with some steps. 
See https://github.com/gmt4/mpvc/wiki/FAQ
